# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""



class veículo:
    def __init__(self,marca,modelo,ano):
        self.marca = marca
        self.modelo = modelo
        self.ano = ano

   def ligar(self):
       print("Veículo ligado")

  def desligar(self):
      print ("Veículo desligado")

class Carro(Veiculo):
    def __init__(self, marca, modelo, ano, numeroDePortas):
        super().__init__(marca, modelo, ano)
        self.numeroDePortas

   def NumeroDePortas(self):
       print("o carro possui: ", self.numeroDePortas)

class moto(veiculo):
   def __init__(self, marca, modelo, ano, cilindradas):
       super().__init__(marca, modelo, ano)
       self.cilindradas = cilindradas

   def cilindradas(self):
       print("A Moto possui: ", self.cilindradas)

class Animal:
    def __init__(self, nome, idade, cor, raca):
        self.nome = nome
        self.idade = idade
        self.cor = cor
        self.raca = raca

    def emitir_som(self):
        print("O som do animal")

class Cachorro(Animal):
    def __init__(self, nome, idade, cor, raca, tamanho_cauda):
        super().__init__(nome, idade, cor, raca)
        self.tamanho_cauda = tamanho_cauda

    def emitir_som(self):
        print("Au au!")

    def rolar(self):
        print(f"{self.nome} está rolando.")

    def deitar(self):
        print(f"{self.nome} está deitado.")

class Gato(Animal):
    def __init__(self, nome, idade, cor, raca, tamanho_cauda):
        super().__init__(nome, idade, cor, raca)
        self.tamanho_cauda = tamanho_cauda

    def emitir_som(self):
        print("Miau!")

    def derrubar_copo(self):
        print(f"{self.nome} derrubou o copo.")

class Passaro(Animal):
    def __init__(self, nome, idade, cor, raca, tipo_bico):
        super().__init__(nome, idade, cor, raca)
        self.tipo_bico = tipo_bico

    def emitir_som(self):
        print("Piu piu!")

    def voar(self):
        print(f"{self.nome} está voando.")

if __name__ == "__main__":
    cachorro1 = Cachorro("Rex", 5, "Marrom", "Vira-lata", "Curta")
    gato1 = Gato("Miau", 3, "Preto", "Siamês", "Longa")
    passaro1 = Passaro("Piu", 1, "Amarelo", "Canário", "Curvo")

    cachorro1.emitir_som()
    cachorro1.rolar()
    cachorro1.deitar()

    gato1.emitir_som()
    gato1.derrubar_copo()

    passaro1.emitir_som()
    passaro1.voar()